/**
 * GuanPlus.Accounting.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface AccountTransactionModel {
    /**
     * id
     */
    id?: string;

    /**
     * 编码
     */
    number?: string;

    /**
     * 交易日期
     */
    accountTransDate?: Date;

    /**
     * 源id
     */
    sourceId?: string;

    /**
     * 联系人
     */
    contact?: models.IdNameModel;

    /**
     * 银行账户
     */
    bankAccount?: models.IdNameModel;

    /**
     * 交易类型
     */
    entityType?: models.AccountTransactionTypeEnumModel;

    /**
     * 实体类型
     */
    sourceEntityType?: models.EntityTypeEnumModel;

    /**
     * 交易总金额
     */
    totalAmount?: number;

    /**
     * 结余
     */
    cashSurplus?: number;

    /**
     * 对账状态
     */
    statementStatus?: models.StatementStatusEnumModel;

    /**
     * 结转状态
     */
    carryForwardStatus?: models.CarryForwardStatusEnumModel;

    accountTransLineItemModels?: Array<models.AccountTransLineItemModel>;

    /**
     * 标签
     */
    tags?: Array<models.TagModel>;

    /**
     * 流水帐附件
     */
    accountAttachmentModels?: Array<models.AccountAttachmentModel>;

}
