/**
 * GuanPlus.Accounting.WebApi
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface ConfirmCarryForwardModel {
    /**
     * 未被选中的各账户统计
     */
    carryForwordAccounts?: Array<models.CarryForwordAccountModel>;

    /**
     * id
     */
    id?: string;

    /**
     * 结转条数
     */
    carryForwardCount?: number;

    /**
     * 结转收入总金额
     */
    carryForwardIncomeAmount?: number;

    /**
     * 结转支出总金额
     */
    carryForwardOutcomeAmount?: number;

    /**
     * 未结转收入总金额
     */
    noCarryForwardIncomeAmount?: number;

    /**
     * 未结转支出总金额
     */
    noCarryForwardOutcomeAmount?: number;

    /**
     * 未结转条数
     */
    noCarryForwardCount?: number;

    /**
     * 包含附件条数
     */
    containsAttachmentCount?: number;

    /**
     * 未包含附件条数
     */
    noContainsAttachmentCount?: number;

    /**
     * 结转日期
     */
    carryForwardOn?: Date;

}
